== Acknowledgements

This book would not have been possible without electricity, beer or kroketten.


[discrete]
== icon:video-camera[] Get the Udemy course for just $10

This book comes with an associated Udemy video tutorial course. As a thankyou for reading this
book you can get the entire course “Create Simple GUI Applications”, with over 2½ hours of
lecture content https://www.udemy.com/create-simple-gui-applications-with-python-and-qt/?couponCode=THANKS50ABL[for just $10]
with the code: `THANKS50ABL`


== Copyright

This book is licensed under the
Creative Commons Attribution Share-alike Non-commercial license (CC BY-NC-SA) +
(C)2015 Martin Fitzpatrick.

- You are free to share unaltered copies of this book with anyone you choose.
- If you modify this book and distribute your altered version it must be distributed under the same license.
- You are not permitted to sell this book or derivatives in any format.
- If you would like to support the author you can _legally_ purchase a copy direct
from the author(s).

Contributions and corrections from readers (CC BY-NC-SA) are most welcome.
